%% System Clean
clear all;
close all;
clc;

%% Load Data

lags_modified = load("Phase_Lags_Modified.mat").phase_lags;
lags_phase = load("Phase_lags_orginal.mat").phase_lags;
load("Gains_Modified.mat")
load("Gains_Orginial.mat")
freq = load("Times_Orginal.mat").df;

%% Figures

figure('Color','w','Position',[400 200 1400 350])

% --- Subplot 1: Gain vs. Frequency ---
subplot(1,2,1)
plot(freq, gains_orginal, '-o', ...
    'LineWidth', 1.5, ...           
    'MarkerSize', 6, ...           
    'MarkerFaceColor', 'b', ...     
    'Color', 'b');                  
hold on;
plot(freq, gains_modified, '-s', ...
    'LineWidth', 1.5, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'r', ...
    'Color', 'r');
hold off;                       
xlabel('Frequency (Hz)', ...
    'FontWeight', 'bold', ...
    'FontSize', 18)
ylabel('Gain', ...
    'FontWeight', 'bold', ...
    'FontSize', 18)
title('(A) Gain vs Frequency', ...
    'FontWeight','bold', ...
    'FontSize', 22)
legend({'Default PID','Altered PID'}, ...
    'Location','best', ...
    'FontSize',12)
grid on;
set(gca, 'FontSize', 12, 'FontWeight', 'bold') % Axis font styling

% --- Subplot 2: Phase vs. Frequency ---
subplot(1,2,2)
plot(freq, lags_phase, '-o', ...
    'LineWidth', 1.5, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'b', ...
    'Color', 'b');
hold on;
plot(freq, lags_modified, '-s', ...
    'LineWidth', 1.5, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'r', ...
    'Color', 'r');
hold off;
xlabel('Frequency (Hz)', ...
    'FontWeight','bold', ...
    'FontSize',22)
ylabel('Phase (deg)', ...
    'FontWeight','bold', ...
    'FontSize',22)
title('(B) Phase vs Frequency', ...
    'FontWeight','bold', ...
    'FontSize',25)
legend({'Default PID','Altered PID'}, ...
    'Location','best', ...
    'FontSize',12)
grid on;
set(gca, 'FontSize', 12, 'FontWeight', 'bold')

